{
 "title": "Printer",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Ink supply level",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_prtMarkerSuppliesDescription",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "prtMarkerSuppliesDescription" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "printer",
     "select": [
      [
       { "params": [ "prtMarkerSuppliesLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ink supply level",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_prtMarkerSuppliesDescription",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "prtMarkerSuppliesDescription" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "printer",
     "query": "SELECT mean(\"prtMarkerSuppliesLevel\") FROM \"printer\" WHERE $timeFilter GROUP BY time($__interval), \"prtMarkerSuppliesDescription\" fill(null)",
     "select": [
      [
       { "params": [ "prtMarkerSuppliesLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages per day moving average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "all pages",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT moving_average(derivative(last(\"total-engine-page-count\"), 1d), 200) FROM \"snmp\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total-color-page-count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1h" ], "type": "derivative" },
       { "params": [ "20" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "color pages",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT moving_average(derivative(last(\"total-color-page-count\"), 1d), 200) FROM \"snmp\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total-engine-page-count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "When will ink run out?",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "printer",
     "query": "ConsumptionRate = from(bucket: \"hlasek_home\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"printer\" and r._field == \"prtMarkerSuppliesLevel\")\n  |> map(fn: (r) => ({r with _value: -r._value}))\n  |> derivative(unit: 1d, nonNegative: true)\n  |> mean()\n\nCurrentLevel = from(bucket: \"hlasek_home\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"printer\" and r._field == \"prtMarkerSuppliesLevel\")\n  |> last()\n\nRateAndCurrent = join(\n  tables: {current_level: CurrentLevel, consumption_rate: ConsumptionRate},\n  on: [\"prtMarkerSuppliesDescription\"]\n)\n\nInkDuration = RateAndCurrent\n  |> map(fn: (r) => ({r with _value: float(v: r._value_current_level) / r._value_consumption_rate}))\n  |> keep(columns: [\"_value\", \"_field\", \"_time\", \"prtMarkerSuppliesDescription\"])\n\nyield InkDuration",
     "select": [
      [
       { "params": [ "prtMarkerSuppliesLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Printed pages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "all pages",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "total-engine-page-count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "color pages",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "total-color-page-count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "When will ink run out?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUSNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "printer",
     "query": "// Compute the daily consumption rate for each cartridge, excluding the negative values that\n// typically mean that the cartridge was actually replaced on that day.\nConsumptionRate = from(bucket: \"hlasek_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"printer\" and r._field == \"prtMarkerSuppliesLevel\")\n  // By flipping the values we then compute the rate of decrease rather than of increase.\n  |> map(fn: (r) => ({r with _value: -r._value}))\n  |> derivative(unit: 1d, nonNegative: true)\n  |> mean()\n\n// For each cartridge, extract the current ink level.\nCurrentLevel = from(bucket: \"hlasek_home\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"printer\" and r._field == \"prtMarkerSuppliesLevel\")\n  |> last()\n\n// Join the above two tables according to the cartridge they represent.\nRateAndCurrent = join(\n  tables: {current_level: CurrentLevel, consumption_rate: ConsumptionRate},\n  on: [\"prtMarkerSuppliesDescription\"]\n)\n\n// Compute the running out date as a linear projection of the consumption rate\n// from the current rate and date.\nRunningOutDateMs = RateAndCurrent\n  // Take the date from the end of the selected time range and convert it to unit.\n  |> map(fn: (r) => ({r with _value: v.timeRangeStop}))\n  |> toUInt()\n  // Add the number of days (in nanoseconds) that the current level of ink will\n  // last at the constant consumption rate.\n  |> map(fn: (r) => ({\n      r with _value: r._value + uint(\n        v: 1000000000.0 * 60.0 * 60.0 * 24.0 *\n        float(v: r._value_current_level) / r._value_consumption_rate\n      )\n    })\n  )\n  // Convert the time to miliseconds so that Grafana can conveniently display it.\n  |> map(fn: (r) => ({r with _value: r._value / uint(v: 1000000)}))\n  |> keep(columns: [\"_value\", \"_field\", \"_time\", \"prtMarkerSuppliesDescription\"])\n\nyield RunningOutDateMs",
     "select": [
      [
       { "params": [ "prtMarkerSuppliesLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ink cost per page",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "printer",
     "query": "BLACK_CARTRIDGE_COST = 32.89\nCOLOR_CARTRIDGE_COST = 63.89\n\nSMOOTHING_DAYS = 120\n\nTotalPagesRate = from(bucket: \"hlasek_home\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"snmp\" and r._field == \"total-engine-page-count\")\n  |> derivative(unit: 1d, nonNegative: true)\n  |> movingAverage(n: SMOOTHING_DAYS)\n\nConsumptionRate = from(bucket: \"hlasek_home\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"printer\" and r._field == \"prtMarkerSuppliesLevel\")\n  |> map(fn: (r) => ({r with _value: -r._value}))\n  |> derivative(unit: 1d, nonNegative: true)\n\nBlackConsumptionRate = ConsumptionRate\n  |> filter(fn: (r) => r.prtMarkerSuppliesDescription == \"black ink HP 3HZ99A\")\n  |> movingAverage(n: SMOOTHING_DAYS)\n\nColorConsumptionRate = ConsumptionRate\n  |> filter(fn: (r) => r.prtMarkerSuppliesDescription != \"black ink HP 3HZ99A\")\n  |> group()\n  |> sort(columns: [\"_time\"])\n  |> timedMovingAverage(every: 1h, period: 1h)\n  |> movingAverage(n: SMOOTHING_DAYS)\n\nJoinedPagesRateAndBlackConsumptionRate = join(\n  tables: {total_pages_rate: TotalPagesRate, consumption_rate: BlackConsumptionRate},\n  on: [\"_time\"]\n)\n\nBlackInkPerPage = JoinedPagesRateAndBlackConsumptionRate\n  |> filter(fn: (r) => r._value_total_pages_rate > 0.01)\n  |> map(fn: (r) => ({r with _value: float(v: r._value_consumption_rate) / float(v: r._value_total_pages_rate)}))\n  |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n\nBlackCostPerPage = BlackInkPerPage\n  |> map(fn: (r) => ({r with _value: r._value / 100.0 * BLACK_CARTRIDGE_COST}))\n  |> map(fn: (r) => ({r with _field: \"black\"}))\n\nJoinedPagesRateAndColorConsumptionRate = join(\n  tables: {total_pages_rate: TotalPagesRate, consumption_rate: ColorConsumptionRate},\n  on: [\"_time\"]\n)\n\nColorInkPerPage = JoinedPagesRateAndColorConsumptionRate\n  |> filter(fn: (r) => r._value_total_pages_rate > 0.01)\n  |> map(fn: (r) => ({r with _value: float(v: r._value_consumption_rate) / float(v: r._value_total_pages_rate)}))\n  |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n\nColorCostPerPage = ColorInkPerPage\n  |> map(fn: (r) => ({r with _value: r._value / 100.0 * COLOR_CARTRIDGE_COST}))\n  |> map(fn: (r) => ({r with _field: \"color\"}))\n\nCostPerPage = join(\n  tables: {black: BlackCostPerPage, color: ColorCostPerPage},\n  on: [\"_time\"]\n)\n  |> map(fn: (r) => ({r with _value: r._value_black + r._value_color}))\n  |> map(fn: (r) => ({r with _field: \"total\"}))\n\nResult = union(tables: [BlackCostPerPage, ColorCostPerPage, CostPerPage])\n\nyield Result",
     "select": [
      [
       { "params": [ "prtMarkerSuppliesLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ink catridge duration based on current usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "alias": "$tag_prtMarkerSuppliesDescription",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "prtMarkerSuppliesDescription" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "printer",
     "query": "from(bucket: \"hlasek_home\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"printer\" and r._field == \"prtMarkerSuppliesLevel\")\n  |> map(fn: (r) => ({r with _value: -r._value}))\n  |> derivative(unit: 1d, nonNegative: true)\n  |> movingAverage(n: 30 * 24)\n  |> filter(fn: (r) => r._value > 0.01)\n  |> map(fn: (r) => ({r with _value: 100.0 / r._value}))\n  |> keep(columns: [\"_value\", \"_time\", \"prtMarkerSuppliesDescription\"])",
     "select": [
      [
       { "params": [ "prtMarkerSuppliesLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Printer Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"uptime\") / 100 FROM \"snmp\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}